Repository Jeongchanyeong/perfitt-client, pull requests merged in 2024-10, with the labels that each got.

#106 feat: add drag event
  src/assets/images/sidemenu-delete.svg
  src/assets/images/sidemenu-share.svg
  src/components/contents/sidemenu/SMChatList.tsx
  src/types/chat.d.ts
Labels: feat

#107 사이드바 및 마이페이지 정보 추가
  src/App.tsx
  src/components/contents/mypage/DeleteUser.tsx
  src/components/contents/mypage/MyPageBottom.tsx
  src/components/contents/mypage/UpdateInfo.tsx
  src/components/contents/mypage/UpdatePassword.tsx
  src/components/contents/mypage/UserInfo.tsx
  src/components/contents/mypage/UserProfile.tsx
  src/components/contents/sidemenu/SideMenu.tsx
  src/components/contents/signin/SignInSocialBtn.tsx
  src/components/contents/signup/SUIdetails.tsx
  src/components/contents/signup/SUInfo.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/router/index.tsx
  src/service/firebase.tsx
  src/stores/UseAutoStore.tsx
  src/stores/UserLoder.tsx
  src/stores/UserState.tsx
  src/types/db.d.ts
  src/types/sign.d.ts
Labels: refactor, feat

#108 feat: 신발 검색 페이지 기능 구현
  src/api/deleteSearchHistory.ts
  src/api/deleteShoeReview.ts
  src/api/getSearchHistory.ts
  src/api/postShoesFind.ts
  src/api/upsertSearchHistory.ts
  src/components/contents/shoerack/SRSearchHistory.tsx
  src/hooks/updateSearchHistory.ts
  src/pages/shoerack/ShoesSearch.tsx
  src/stores/search.store.ts
  src/types/db.d.ts
Labels: feat

#109 fix : 오류 수정 및 framer-motion install
  package-lock.json
  package.json
  src/components/contents/mypage/UpdateInfo.tsx
  src/types/sign.d.ts
Labels: bug
