Repository Jeongchanyeong/perfitt-client, pull requests merged in 2024-09, with the labels that each got.

#3 feat: 프로젝트 초기 세팅
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/vite.svg
  src/App.tsx
  src/css/tailwind.css
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: setting

#5 feat: ESLint, Prettier 설정
  .prettierrc.json
  eslint.config.js
  package-lock.json
  package.json
Labels: setting

#12 feat: 공통 Button 구현
  src/components/common/Button.tsx
Labels: feat

#10 feat: default layout 생성 #6
  src/layout/DefaultLayout.tsx
  src/router/index.tsx
Labels: feat

#16 feat: font import
  src/css/fonts.css
  src/index.css
  src/layout/DefaultLayout.tsx
Labels: feat

#20 Feature/default layout
  src/assets/images/images.ts
  src/assets/images/plus-circle-icon.svg
  src/assets/images/plus-icon.svg
  src/assets/images/polygon-icon.svg
  src/assets/images/shoe-search.svg
  src/assets/images/user-icon.svg
  src/components/common/Button.tsx
  src/components/contents/SREmpty.tsx
  src/components/contents/SRShoeBox.tsx
  src/components/contents/SRShoeRack.tsx
  src/components/contents/SRUserInfo.tsx
  src/layout/DefaultLayout.tsx
  src/pages/ShoeRack.tsx
Labels: style

#18 feat: 신발장 메인 페이지 UI 구현 - #17
  src/assets/images/images.ts
  src/assets/images/plus-circle-icon.svg
  src/assets/images/plus-icon.svg
  src/assets/images/polygon-icon.svg
  src/assets/images/shoe-search.svg
  src/assets/images/user-icon.svg
  src/components/contents/SREmpty.tsx
  src/components/contents/SRShoeBox.tsx
  src/components/contents/SRShoeRack.tsx
  src/components/contents/SRUserInfo.tsx
  src/pages/ShoeRack.tsx
Labels: feat

#21 feat: 공통 Header 구현
  src/components/common/Header.tsx
Labels: feat

#23 fix: Header rightChild optional 누락 수정
  src/components/common/Header.tsx
Labels: feat

#25 Feature/onboarding
  src/assets/images/onboarding1.jpg
  src/assets/images/onboarding2.jpg
  src/pages/OnBoarding.tsx
  src/router/index.tsx
Labels: feat

#29 feat: myfootinfo css
  src/assets/images/myfoot.jpg
  src/pages/MyFootInfo.tsx
  src/pages/OnBoarding.tsx
Labels: style

#27 feat: bridge css
  src/assets/images/bridge.jpg
  src/pages/Bridge.tsx
  src/pages/OnBoarding.tsx
Labels: style

#30 fix: Image rounded cut
  src/pages/Bridge.tsx
Labels: style

#34 feat: 채팅 UI 구현
  package-lock.json
  package.json
  public/vite.svg
  src/App.tsx
  src/assets/images/brand.svg
  src/assets/images/export-icon.svg
  src/assets/images/gallery-Icon.svg
  src/assets/images/hamburger.svg
  src/assets/images/images.ts
  src/assets/images/perfitt-logo.svg
  src/assets/images/question-mark.svg
  src/assets/images/right-arrow-long.svg
  src/assets/images/right-arrow-short.svg
  src/assets/images/thumbs-down.svg
  src/assets/images/up-arrow.svg
  src/components/contents/chat/ChatContainer.tsx
  src/components/contents/chat/ChatInput.tsx
  src/components/contents/chat/chatwindow/ChatWindow.tsx
  src/components/contents/chat/chatwindow/MeasureFoot.tsx
  src/components/contents/chat/chatwindow/bottomsheet/BottomSheet.tsx
  src/components/contents/chat/chatwindow/bottomsheet/brand/BrandItemsContainter.tsx
  src/components/contents/chat/chatwindow/bottomsheet/brand/BrandLabel.tsx
  src/components/contents/chat/chatwindow/bottomsheet/brand/BrandPLP.tsx
  src/components/contents/chat/chatwindow/bottomsheet/brand/CategoryFilter.tsx
  src/components/contents/chat/chatwindow/bottomsheet/product/ProductPLP.tsx
  src/components/contents/chat/chatwindow/card/BrandCard.tsx
  src/components/contents/chat/chatwindow/card/CardContainer.tsx
  src/components/contents/chat/chatwindow/card/MoreButton.tsx
  src/components/contents/chat/chatwindow/card/ProductFilter.tsx
  src/components/contents/chat/chatwindow/keyword/KeyWordButton.tsx
  src/components/contents/chat/chatwindow/keyword/KeyWordSelector.tsx
  src/components/contents/chat/chatwindow/message/AIMessage.tsx
  src/components/contents/chat/chatwindow/message/MyMessage.tsx
  tailwind.config.js
Labels: style

#42 feat: 신발 등록 페이지 UI 구현
  src/assets/images/images.ts
  src/assets/images/star-fill-icon.svg
  src/assets/images/star-icon.svg
  src/components/contents/SROptionSelector.tsx
  src/components/contents/SRShoeBox.tsx
  src/components/contents/SRShoeInfo.tsx
  src/components/contents/SRShoeRack.tsx
  src/pages/AddShoes.tsx
Labels: feat

#43 신발 등록 - 파일 이름 변경, 이미지 import
  src/assets/images/images.ts
  src/pages/ShoesReviewEdit.tsx
Labels: refactor

#44 chore: 신발 등록 페이지 파일 이름 변경
  src/pages/ShoesReviewEdit.tsx
Labels: refactor

#46 feat: 신발 상세 페이지 UI 구현, 신발 등록/수정 페이지 속성 추가
  src/pages/ShoesDetail.tsx
  src/pages/ShoesReviewEdit.tsx
Labels: feat

#50 feat: 회원가입 페이지 UI 구현
  src/assets/images/down-arrow-icon.svg
  src/assets/images/images.ts
  src/components/contents/signup/SUInput.tsx
  src/components/contents/signup/SUSelect.tsx
  src/pages/SignUp.tsx
  src/types/sign.d.ts
Labels: feat

#51 fix: Signin file 생성
  src/components/contents/signin/SignInAuthList.tsx
  src/components/contents/signin/SignInAutoKeyword.tsx
  src/components/contents/signin/SignInSocialBtn.tsx
Labels: refactor

#57 회원가입 UI 구현 및 기능 구현
  package-lock.json
  package.json
  src/assets/images/icon_info_blue400.png
  src/components/contents/signup/SUIbtn.tsx
  src/components/contents/signup/SUIdetails.tsx
  src/components/contents/signup/SUInfo.tsx
  src/pages/SignUp.tsx
  src/types/sign.d.ts
Labels: feat

#60 feat: 신발 검색 페이지 UI 구현, 신발장 폴더 추가, 변수/타입 추가
  src/assets/images/camera-icon.svg
  src/assets/images/left-arrow.icon.svg
  src/assets/images/search-icon.svg
  src/assets/images/shoe-silhouette.png
  src/assets/images/trash-icon.svg
  src/assets/images/x-gray-icon.svg
  src/components/contents/SREmpty.tsx
  src/components/contents/SRShoeBox.tsx
  src/components/contents/SRShoeInfo.tsx
  src/components/contents/SRUserInfo.tsx
  src/components/contents/shoerack/SREmpty.tsx
  src/components/contents/shoerack/SROptionSelector.tsx
  src/components/contents/shoerack/SRSearchHistory.tsx
  src/components/contents/shoerack/SRShoeBox.tsx
  src/components/contents/shoerack/SRShoeInfo.tsx
  src/components/contents/shoerack/SRShoeRack.tsx
  src/pages/ShoeRack.tsx
  src/pages/ShoesDetail.tsx
  src/pages/ShoesReviewEdit.tsx
  src/pages/shoerack/ShoeRack.tsx
  src/pages/shoerack/ShoesReviewDetail.tsx
  src/pages/shoerack/ShoesReviewEdit.tsx
  src/pages/shoerack/ShoesSearch.tsx
  src/types/shoerack.d.ts
Labels: feat

#59 feat: 공통 Header 수정, Default Layout padding 값 수정
  index.html
  src/assets/images/images.ts
  src/assets/images/menu-icon.svg
  src/assets/images/vertical-menu-icon.svg
  src/components/common/Header.tsx
  src/components/contents/chat/chatwindow/ChatWindow.tsx
  src/css/fonts.css
  src/layout/DefaultLayout.tsx
  src/pages/Like.tsx
  src/pages/MyFootInfo.tsx
  src/pages/OnBoarding.tsx
Labels: feat

#66 feat: 채팅 응답 API 연결 (brand)
  package-lock.json
  package.json
  src/api/brand/ GetBrandApi.ts
  src/api/chat/FetchChatResponseApi.ts
  src/assets/images/images.ts
  src/components/contents/chat/ChatContainer.tsx
  src/components/contents/chat/chatwindow/ChatWindow.tsx
  src/components/contents/chat/chatwindow/bottomsheet/BottomSheet.tsx
  src/components/contents/chat/chatwindow/bottomsheet/BrandPLP.tsx
  src/components/contents/chat/chatwindow/bottomsheet/ProductPLP.tsx
  src/components/contents/chat/chatwindow/bottomsheet/brand/BrandItemsContainter.tsx
  src/components/contents/chat/chatwindow/bottomsheet/brand/BrandLabel.tsx
  src/components/contents/chat/chatwindow/bottomsheet/brand/BrandPLP.tsx
  src/components/contents/chat/chatwindow/bottomsheet/brand/CategoryFilter.tsx
  src/components/contents/chat/chatwindow/bottomsheet/product/ProductPLP.tsx
  src/components/contents/chat/chatwindow/card/BrandCard.tsx
  src/components/contents/chat/chatwindow/card/CardContainer.tsx
  src/components/contents/chat/chatwindow/card/ProductFilter.tsx
  src/components/contents/chat/chatwindow/card/ProductList.tsx
  src/components/contents/chat/chatwindow/keyword/KeyWordSelector.tsx
  src/components/contents/chat/chatwindow/message/AIContainer.tsx
  src/components/contents/chat/chatwindow/message/AIMessage.tsx
  src/hooks/useChatMutation.ts
  src/types/chat.d.ts
  src/utils/chat/AIData.ts
Labels: feat

#64 feat: 유효성 검사 기능 및 스타일 수정
  package-lock.json
  package.json
  src/App.tsx
  src/components/contents/signin/SignInSocialBtn.tsx
  src/components/contents/signup/SUIdetails.tsx
  src/components/contents/signup/SUInfo.tsx
  src/components/contents/signup/SUInput.tsx
  src/components/contents/signup/SUSelect.tsx
  src/pages/SignIn.tsx
  src/router/index.tsx
  src/service/AuthContext.tsx
  src/service/AuthProvider.tsx
  src/service/Protected_route.tsx
  src/service/firebase.tsx
  src/types/sign.d.ts
Labels: feat

#67 Feature/myfoot jpg를 gif로 변경
  src/assets/images/foot-loading.gif
  src/assets/images/myfoot.jpg
  src/assets/images/sidemenu-ChatCircle.svg
  src/assets/images/sidemenu-plus.svg
  src/components/contents/sidemenu/Last7Days.tsx
  src/components/contents/sidemenu/Question.tsx
  src/components/contents/sidemenu/SideMenu.tsx
  src/components/contents/sidemenu/SideMenuBottom.tsx
  src/components/contents/sidemenu/SideMenuTop.tsx
  src/components/contents/sidemenu/TodayChatList.tsx
  src/pages/MyFootInfo.tsx
Labels: style

#69 feat: Splash Screen UI 구현
  src/assets/images/footprint.svg
  src/assets/images/images.ts
  src/assets/images/perfitt-circle-logo.svg
  src/assets/images/perfitt-logo.svg
  src/components/contents/chat/chatwindow/message/AIMessage.tsx
  src/pages/SplashScreen.tsx
  tailwind.config.js
Labels: feat

#72 feat: 채팅 응답에 따른 brand와 product 데이터 처리 및 렌더링 구현
  package-lock.json
  package.json
  src/api/chat/FetchChatResponseApi.ts
  src/api/chat/getHelloApi.ts
  src/assets/images/images.ts
  src/components/contents/chat/ChatContainer.tsx
  src/components/contents/chat/ChatInput.tsx
  src/components/contents/chat/chatwindow/ChatWindow.tsx
  src/components/contents/chat/chatwindow/card/BrandCard.tsx
  src/components/contents/chat/chatwindow/card/CardContainer.tsx
  src/components/contents/chat/chatwindow/card/ProductItem.tsx
  src/components/contents/chat/chatwindow/card/ProductList.tsx
  src/components/contents/chat/chatwindow/card/ShareDislikeButton.tsx
  src/components/contents/chat/chatwindow/message/AIContainer.tsx
  src/components/contents/chat/chatwindow/message/AIMessage.tsx
  src/types/chat.d.ts
Labels: feat

#73 feat: onBoarding type animation 적용
  package-lock.json
  package.json
  src/assets/images/onboarding_plp1.jpg
  src/assets/images/onboarding_plp2.jpg
  src/pages/OnBoarding.tsx
Labels: feat

#75 feat: not found UI 구현
  src/assets/images/footprint-404.svg
  src/pages/NotFound.tsx
Labels: feat

#80 chore: icons 폴더 추가, 위치 변경
  src/assets/icons/chat-icon.svg
  src/assets/icons/menu-icon.svg
  src/assets/icons/plus-mini-icon.svg
  src/assets/icons/user-border-icon.svg
  src/assets/images/foot-scanning.png
  src/assets/images/images.ts
  src/assets/images/ob-list1.png
  src/assets/images/ob-list2.png
  src/assets/images/onboarding1.jpg
  src/assets/images/onboarding2.jpg
  src/assets/images/onboarding_plp1.jpg
  src/assets/images/onboarding_plp2.jpg
  src/assets/images/plus-icon.svg
Labels: feat

#86 feat: 누락 코드 반영 및 코드 임시 변경
  package-lock.json
  src/api/signin/getRecomendListApi.ts
  src/api/signin/getRecommendApi.ts
  src/components/contents/chat/chatwindow/ChatWindow.tsx
  src/components/contents/chat/chatwindow/keyword/KeyWordSelector.tsx
  src/components/contents/signin/SignInAuthList.tsx
  src/components/contents/signin/SignInAutoKeyword.tsx
  src/components/contents/signin/SignInSocialBtn.tsx
  src/pages/SignIn.tsx
  src/router/index.tsx
  src/service/firebase.tsx
Labels: feat

#88 feat: 내 발 측정하기 api
  index.html
  src/pages/MyFootInfo.tsx
Labels: feat

#90 feat: AI 채팅 디자인 임시 변경
  src/pages/SignIn.tsx
Labels: feat

#92 feat: User, AI 메세지 firebase 연결
  src/components/contents/sidemenu/SideMenu.tsx
  src/components/contents/signin/SignInAutoKeyword.tsx
  src/pages/Chat.tsx
  src/pages/OnBoarding.tsx
  src/pages/SignIn.tsx
  src/service/CreateNewChat.ts
Labels: feat

#93 feat:bridge 연결
  src/assets/images/bridge.jpg
  src/components/common/ProductCard.tsx
  src/hooks/getPartnerBrand.ts
  src/pages/Bridge.tsx
  src/router/index.tsx
Labels: feat

#94 Feat: sign-up modal 기능구현완료 및 수정
  src/App.tsx
  src/assets/icons/bar.svg
  src/components/common/ModalBar.tsx
  src/components/contents/signin/SignInSocialBtn.tsx
  src/components/contents/signup/SUISelectCss.tsx
  src/components/contents/signup/SUIdetails.tsx
  src/components/contents/signup/SUInfo.tsx
  src/components/contents/signup/SUSelect.tsx
  src/pages/SignUp.tsx
  src/service/Protected_route.tsx
  src/types/sign.d.ts
Labels: feat

#95 좋아요, 최근본 ui 구현 및 기능 추가 완료
  src/components/common/ProductCard.tsx
  src/components/contents/Like/LikeBrand.tsx
  src/components/contents/Like/LikeHeader.tsx
  src/components/contents/item/ItemToggle.tsx
  src/components/contents/item/LatestItem.tsx
  src/components/contents/item/LikeBrand.tsx
  src/components/contents/item/LikeBrandList.tsx
  src/components/contents/item/LikeItem.tsx
  src/components/contents/item/LikeProduct.tsx
  src/pages/Item.tsx
  src/router/index.tsx
  src/types/like.d.ts
Labels: feat, style

#96 로그아웃 기능 추가
  src/components/contents/sidemenu/SideMenu.tsx
  src/components/contents/signin/Logout.tsx
Labels: feat

#98 feat: AutoKeyword 채팅창 연결
  src/api/brand/GetBrandApi.ts
  src/components/contents/chat/chatwindow/bottomsheet/BrandPLP.tsx
  src/components/contents/signin/SignInAutoKeyword.tsx
  src/hooks/useChatMutation.ts
  src/pages/Chat.tsx
Labels: feat

#102 refactor: 사이드 메뉴 modal 수정
  src/api/deleteShoeReview.tsx
  src/api/getProduct.ts
  src/api/getShoeRack.ts
  src/api/getShoeReview.ts
  src/api/getUserInfo.ts
  src/api/upsertProduct.ts
  src/api/upsertShoeReview.ts
  src/assets/icons/pencil-icon.svg
  src/assets/icons/pencil-red-icon.svg
  src/assets/icons/trash-icon.svg
  src/assets/icons/trash-red-icon.svg
  src/assets/images/vertical-menu-icon.svg
  src/components/common/Header.tsx
  src/components/contents/chat/ChatHeader.tsx
  src/components/contents/shoerack/SRDMenu.tsx
  src/components/contents/shoerack/SRDMenuDetail.tsx
  src/components/contents/shoerack/SREmpty.tsx
  src/components/contents/shoerack/SRShoeBox.tsx
  src/components/contents/shoerack/SRShoeInfo.tsx
  src/components/contents/shoerack/SRShoeRack.tsx
  src/components/contents/sidemenu/SideMenu.tsx
  src/layout/HeaderLayout.tsx
  src/pages/shoerack/ShoeRack.tsx
  src/pages/shoerack/ShoesReviewDetail.tsx
  src/pages/shoerack/ShoesReviewEdit.tsx
  src/pages/shoerack/ShoesSearch.tsx
  src/router/index.tsx
  src/stores/shoerack.store.ts
  src/stores/user.store.ts
  src/types/db.d.ts
  src/types/header.d.ts
  src/types/shoerack.d.ts
Labels: refactor

#100 feat: 신발장 기능 구현
  src/api/deleteShoeReview.tsx
  src/api/getProduct.ts
  src/api/getShoeRack.ts
  src/api/getShoeReview.ts
  src/api/getUserInfo.ts
  src/api/upsertProduct.ts
  src/api/upsertShoeReview.ts
  src/assets/icons/pencil-icon.svg
  src/assets/icons/pencil-red-icon.svg
  src/assets/icons/trash-icon.svg
  src/assets/icons/trash-red-icon.svg
  src/assets/images/vertical-menu-icon.svg
  src/components/contents/shoerack/SRDMenu.tsx
  src/components/contents/shoerack/SRDMenuDetail.tsx
  src/components/contents/shoerack/SREmpty.tsx
  src/components/contents/shoerack/SRShoeBox.tsx
  src/components/contents/shoerack/SRShoeInfo.tsx
  src/components/contents/shoerack/SRShoeRack.tsx
  src/pages/shoerack/ShoeRack.tsx
  src/pages/shoerack/ShoesReviewDetail.tsx
  src/pages/shoerack/ShoesReviewEdit.tsx
  src/pages/shoerack/ShoesSearch.tsx
  src/router/index.tsx
  src/stores/shoerack.store.ts
  src/stores/user.store.ts
  src/types/db.d.ts
  src/types/shoerack.d.ts
Labels: feat

#104 refactor: logout 파일 삭제
  src/components/contents/signin/Logout.tsx
Labels: refactor

#105 chore: 주석 수정
  src/service/firebase.tsx
Labels: refactor
